steps:
  - name: hashicorp/terraform:1.6
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -input=false

  - name: hashicorp/terraform:1.6
    args: ["fmt", "-check", "-recursive"]

  - name: hashicorp/terraform:1.6
    args: ["validate"]

  - name: hashicorp/terraform:1.6
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -input=false -no-color

options:
  logging: CLOUD_LOGGING_ONLY

#test
